# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'shortcut_cliento.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QSizePolicy,
    QStackedWidget, QToolButton, QWidget)

class Ui_stream_cliento(object):
    def setupUi(self, stream_cliento):
        if not stream_cliento.objectName():
            stream_cliento.setObjectName(u"stream_cliento")
        stream_cliento.resize(800, 580)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stream_cliento.sizePolicy().hasHeightForWidth())
        stream_cliento.setSizePolicy(sizePolicy)
        stream_cliento.setMinimumSize(QSize(800, 580))
        stream_cliento.setMaximumSize(QSize(800, 580))
        self.Button_stackedWidget = QStackedWidget(stream_cliento)
        self.Button_stackedWidget.setObjectName(u"Button_stackedWidget")
        self.Button_stackedWidget.setEnabled(True)
        self.Button_stackedWidget.setGeometry(QRect(10, 10, 780, 560))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Button_stackedWidget.sizePolicy().hasHeightForWidth())
        self.Button_stackedWidget.setSizePolicy(sizePolicy1)
        self.Button_stackedWidget.setMinimumSize(QSize(780, 560))
        self.Button_stackedWidget.setMaximumSize(QSize(780, 560))
        self.Button_stackedWidget.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(5)
        self.Button_stackedWidget.setFont(font)
        self.Button_stackedWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Button_stackedWidget.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_stackedWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.Button_stackedWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_stackedWidget.setStyleSheet(u"")
        self.Button_stackedWidget.setLocale(QLocale(QLocale.Russian, QLocale.Russia))
        self.Button_stackedWidget.setFrameShape(QFrame.Shape.WinPanel)
        self.Button_stackedWidget.setFrameShadow(QFrame.Shadow.Plain)
        self.Button_stackedWidget.setLineWidth(1)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.page_1.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy1)
        self.page_1.setMaximumSize(QSize(760, 540))
        self.page_1.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.page_1.setToolTipDuration(-1)
        self.page_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.page_1.setAutoFillBackground(False)
        self.page_1.setStyleSheet(u"")
        self.Button_frame_01 = QFrame(self.page_1)
        self.Button_frame_01.setObjectName(u"Button_frame_01")
        self.Button_frame_01.setEnabled(True)
        self.Button_frame_01.setGeometry(QRect(10, 10, 750, 530))
        sizePolicy.setHeightForWidth(self.Button_frame_01.sizePolicy().hasHeightForWidth())
        self.Button_frame_01.setSizePolicy(sizePolicy)
        self.Button_frame_01.setMaximumSize(QSize(750, 530))
        self.Button_frame_01.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_frame_01.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_frame_01.setFrameShadow(QFrame.Shadow.Plain)
        self.Button_frame_01.setLineWidth(2)
        self.Button_frame_01.setMidLineWidth(0)
        self.gridLayout = QGridLayout(self.Button_frame_01)
        self.gridLayout.setObjectName(u"gridLayout")
        self.butt_toolB_01 = QToolButton(self.Button_frame_01)
        self.butt_toolB_01.setObjectName(u"butt_toolB_01")
        self.butt_toolB_01.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_01.sizePolicy().hasHeightForWidth())
        self.butt_toolB_01.setSizePolicy(sizePolicy1)
        self.butt_toolB_01.setMinimumSize(QSize(150, 150))
        self.butt_toolB_01.setMaximumSize(QSize(150, 150))
        self.butt_toolB_01.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_01.setIconSize(QSize(70, 70))
        self.butt_toolB_01.setCheckable(False)
        self.butt_toolB_01.setChecked(False)
        self.butt_toolB_01.setAutoRepeatDelay(600)
        self.butt_toolB_01.setAutoRepeatInterval(300)
        self.butt_toolB_01.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_01.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_01.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_01, 0, 0, 1, 1)

        self.butt_toolB_02 = QToolButton(self.Button_frame_01)
        self.butt_toolB_02.setObjectName(u"butt_toolB_02")
        self.butt_toolB_02.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_02.sizePolicy().hasHeightForWidth())
        self.butt_toolB_02.setSizePolicy(sizePolicy1)
        self.butt_toolB_02.setMinimumSize(QSize(150, 150))
        self.butt_toolB_02.setMaximumSize(QSize(150, 150))
        self.butt_toolB_02.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_02.setIconSize(QSize(70, 70))
        self.butt_toolB_02.setCheckable(False)
        self.butt_toolB_02.setChecked(False)
        self.butt_toolB_02.setAutoRepeatDelay(600)
        self.butt_toolB_02.setAutoRepeatInterval(300)
        self.butt_toolB_02.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_02.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_02.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_02, 0, 1, 1, 1)

        self.butt_toolB_08 = QToolButton(self.Button_frame_01)
        self.butt_toolB_08.setObjectName(u"butt_toolB_08")
        self.butt_toolB_08.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_08.sizePolicy().hasHeightForWidth())
        self.butt_toolB_08.setSizePolicy(sizePolicy1)
        self.butt_toolB_08.setMinimumSize(QSize(150, 150))
        self.butt_toolB_08.setMaximumSize(QSize(150, 150))
        self.butt_toolB_08.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_08.setIconSize(QSize(70, 70))
        self.butt_toolB_08.setCheckable(False)
        self.butt_toolB_08.setChecked(False)
        self.butt_toolB_08.setAutoRepeatDelay(600)
        self.butt_toolB_08.setAutoRepeatInterval(300)
        self.butt_toolB_08.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_08.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_08.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_08, 1, 3, 1, 1)

        self.butt_toolB_12 = QToolButton(self.Button_frame_01)
        self.butt_toolB_12.setObjectName(u"butt_toolB_12")
        self.butt_toolB_12.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_12.sizePolicy().hasHeightForWidth())
        self.butt_toolB_12.setSizePolicy(sizePolicy1)
        self.butt_toolB_12.setMinimumSize(QSize(150, 150))
        self.butt_toolB_12.setMaximumSize(QSize(150, 150))
        self.butt_toolB_12.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_12.setIconSize(QSize(70, 70))
        self.butt_toolB_12.setCheckable(False)
        self.butt_toolB_12.setChecked(False)
        self.butt_toolB_12.setAutoRepeatDelay(600)
        self.butt_toolB_12.setAutoRepeatInterval(300)
        self.butt_toolB_12.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_12.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_12.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_12, 2, 3, 1, 1)

        self.butt_toolB_09 = QToolButton(self.Button_frame_01)
        self.butt_toolB_09.setObjectName(u"butt_toolB_09")
        self.butt_toolB_09.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_09.sizePolicy().hasHeightForWidth())
        self.butt_toolB_09.setSizePolicy(sizePolicy1)
        self.butt_toolB_09.setMinimumSize(QSize(150, 150))
        self.butt_toolB_09.setMaximumSize(QSize(150, 150))
        self.butt_toolB_09.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_09.setIconSize(QSize(70, 70))
        self.butt_toolB_09.setCheckable(False)
        self.butt_toolB_09.setChecked(False)
        self.butt_toolB_09.setAutoRepeatDelay(600)
        self.butt_toolB_09.setAutoRepeatInterval(300)
        self.butt_toolB_09.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_09.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_09.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_09, 2, 0, 1, 1)

        self.butt_toolB_05 = QToolButton(self.Button_frame_01)
        self.butt_toolB_05.setObjectName(u"butt_toolB_05")
        self.butt_toolB_05.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_05.sizePolicy().hasHeightForWidth())
        self.butt_toolB_05.setSizePolicy(sizePolicy1)
        self.butt_toolB_05.setMinimumSize(QSize(150, 150))
        self.butt_toolB_05.setMaximumSize(QSize(150, 150))
        self.butt_toolB_05.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_05.setIconSize(QSize(70, 70))
        self.butt_toolB_05.setCheckable(False)
        self.butt_toolB_05.setChecked(False)
        self.butt_toolB_05.setAutoRepeatDelay(600)
        self.butt_toolB_05.setAutoRepeatInterval(300)
        self.butt_toolB_05.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_05.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_05.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_05, 1, 0, 1, 1)

        self.butt_toolB_04 = QToolButton(self.Button_frame_01)
        self.butt_toolB_04.setObjectName(u"butt_toolB_04")
        self.butt_toolB_04.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_04.sizePolicy().hasHeightForWidth())
        self.butt_toolB_04.setSizePolicy(sizePolicy1)
        self.butt_toolB_04.setMinimumSize(QSize(150, 150))
        self.butt_toolB_04.setMaximumSize(QSize(150, 150))
        self.butt_toolB_04.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_04.setIconSize(QSize(70, 70))
        self.butt_toolB_04.setCheckable(False)
        self.butt_toolB_04.setChecked(False)
        self.butt_toolB_04.setAutoRepeatDelay(600)
        self.butt_toolB_04.setAutoRepeatInterval(300)
        self.butt_toolB_04.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_04.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_04.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_04, 0, 3, 1, 1)

        self.butt_toolB_03 = QToolButton(self.Button_frame_01)
        self.butt_toolB_03.setObjectName(u"butt_toolB_03")
        self.butt_toolB_03.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_03.sizePolicy().hasHeightForWidth())
        self.butt_toolB_03.setSizePolicy(sizePolicy1)
        self.butt_toolB_03.setMinimumSize(QSize(150, 150))
        self.butt_toolB_03.setMaximumSize(QSize(150, 150))
        self.butt_toolB_03.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_03.setIconSize(QSize(70, 70))
        self.butt_toolB_03.setCheckable(False)
        self.butt_toolB_03.setChecked(False)
        self.butt_toolB_03.setAutoRepeatDelay(600)
        self.butt_toolB_03.setAutoRepeatInterval(300)
        self.butt_toolB_03.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_03.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_03.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_03, 0, 2, 1, 1)

        self.butt_toolB_10 = QToolButton(self.Button_frame_01)
        self.butt_toolB_10.setObjectName(u"butt_toolB_10")
        self.butt_toolB_10.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_10.sizePolicy().hasHeightForWidth())
        self.butt_toolB_10.setSizePolicy(sizePolicy1)
        self.butt_toolB_10.setMinimumSize(QSize(150, 150))
        self.butt_toolB_10.setMaximumSize(QSize(150, 150))
        self.butt_toolB_10.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_10.setIconSize(QSize(70, 70))
        self.butt_toolB_10.setCheckable(False)
        self.butt_toolB_10.setChecked(False)
        self.butt_toolB_10.setAutoRepeatDelay(600)
        self.butt_toolB_10.setAutoRepeatInterval(300)
        self.butt_toolB_10.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_10.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_10.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_10, 2, 1, 1, 1)

        self.butt_toolB_07 = QToolButton(self.Button_frame_01)
        self.butt_toolB_07.setObjectName(u"butt_toolB_07")
        self.butt_toolB_07.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_07.sizePolicy().hasHeightForWidth())
        self.butt_toolB_07.setSizePolicy(sizePolicy1)
        self.butt_toolB_07.setMinimumSize(QSize(150, 150))
        self.butt_toolB_07.setMaximumSize(QSize(150, 150))
        self.butt_toolB_07.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_07.setIconSize(QSize(70, 70))
        self.butt_toolB_07.setCheckable(False)
        self.butt_toolB_07.setChecked(False)
        self.butt_toolB_07.setAutoRepeatDelay(600)
        self.butt_toolB_07.setAutoRepeatInterval(300)
        self.butt_toolB_07.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_07.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_07.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_07, 1, 2, 1, 1)

        self.butt_toolB_11 = QToolButton(self.Button_frame_01)
        self.butt_toolB_11.setObjectName(u"butt_toolB_11")
        self.butt_toolB_11.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_11.sizePolicy().hasHeightForWidth())
        self.butt_toolB_11.setSizePolicy(sizePolicy1)
        self.butt_toolB_11.setMinimumSize(QSize(150, 150))
        self.butt_toolB_11.setMaximumSize(QSize(150, 150))
        self.butt_toolB_11.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_11.setIconSize(QSize(70, 70))
        self.butt_toolB_11.setCheckable(False)
        self.butt_toolB_11.setChecked(False)
        self.butt_toolB_11.setAutoRepeatDelay(600)
        self.butt_toolB_11.setAutoRepeatInterval(300)
        self.butt_toolB_11.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_11.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_11.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_11, 2, 2, 1, 1)

        self.butt_toolB_06 = QToolButton(self.Button_frame_01)
        self.butt_toolB_06.setObjectName(u"butt_toolB_06")
        self.butt_toolB_06.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.butt_toolB_06.sizePolicy().hasHeightForWidth())
        self.butt_toolB_06.setSizePolicy(sizePolicy1)
        self.butt_toolB_06.setMinimumSize(QSize(150, 150))
        self.butt_toolB_06.setMaximumSize(QSize(150, 150))
        self.butt_toolB_06.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_06.setIconSize(QSize(70, 70))
        self.butt_toolB_06.setCheckable(False)
        self.butt_toolB_06.setChecked(False)
        self.butt_toolB_06.setAutoRepeatDelay(600)
        self.butt_toolB_06.setAutoRepeatInterval(300)
        self.butt_toolB_06.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_06.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_06.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_06, 1, 1, 1, 1)

        self.Button_stackedWidget.addWidget(self.page_1)

        self.retranslateUi(stream_cliento)

        self.Button_stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(stream_cliento)
    # setupUi

    def retranslateUi(self, stream_cliento):
        self.butt_toolB_01.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_01.setProperty("shadowPreset", QCoreApplication.translate("stream_cliento", u"button", None))
        self.butt_toolB_02.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_02.setProperty("shadowPreset", QCoreApplication.translate("stream_cliento", u"glow_pink", None))
        self.butt_toolB_08.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_12.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_09.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_05.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_04.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_03.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_10.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_07.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_11.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        self.butt_toolB_06.setText(QCoreApplication.translate("stream_cliento", u"...", None))
        pass
    # retranslateUi

