# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'shortcut_bandito.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QHeaderView, QKeySequenceEdit,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QStackedWidget, QTabWidget, QToolButton, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_stream_bandito(object):
    def setupUi(self, stream_bandito):
        if not stream_bandito.objectName():
            stream_bandito.setObjectName(u"stream_bandito")
        stream_bandito.setWindowModality(Qt.WindowModality.NonModal)
        stream_bandito.resize(900, 680)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stream_bandito.sizePolicy().hasHeightForWidth())
        stream_bandito.setSizePolicy(sizePolicy)
        stream_bandito.setMinimumSize(QSize(900, 680))
        stream_bandito.setMaximumSize(QSize(900, 680))
        stream_bandito.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        stream_bandito.setWindowOpacity(1.000000000000000)
        self.frame = QFrame(stream_bandito)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 900, 680))
        self.frame.setMinimumSize(QSize(900, 680))
        self.frame.setMaximumSize(QSize(980, 680))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.left_layout = QVBoxLayout()
        self.left_layout.setSpacing(10)
        self.left_layout.setObjectName(u"left_layout")
        self.left_layout.setContentsMargins(0, -1, 0, 0)
        self.Button_stackedWidget = QStackedWidget(self.frame)
        self.Button_stackedWidget.setObjectName(u"Button_stackedWidget")
        self.Button_stackedWidget.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Button_stackedWidget.sizePolicy().hasHeightForWidth())
        self.Button_stackedWidget.setSizePolicy(sizePolicy1)
        self.Button_stackedWidget.setMinimumSize(QSize(600, 400))
        self.Button_stackedWidget.setMaximumSize(QSize(600, 430))
        self.Button_stackedWidget.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(5)
        self.Button_stackedWidget.setFont(font)
        self.Button_stackedWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Button_stackedWidget.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_stackedWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.Button_stackedWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_stackedWidget.setLocale(QLocale(QLocale.Russian, QLocale.Russia))
        self.Button_stackedWidget.setFrameShape(QFrame.Shape.WinPanel)
        self.Button_stackedWidget.setFrameShadow(QFrame.Shadow.Plain)
        self.Button_stackedWidget.setLineWidth(1)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.page_1.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy2)
        self.page_1.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.page_1.setToolTipDuration(-1)
        self.page_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.page_1.setAutoFillBackground(False)
        self.gridLayout_2 = QGridLayout(self.page_1)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.Button_frame_01 = QFrame(self.page_1)
        self.Button_frame_01.setObjectName(u"Button_frame_01")
        self.Button_frame_01.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.Button_frame_01.sizePolicy().hasHeightForWidth())
        self.Button_frame_01.setSizePolicy(sizePolicy1)
        self.Button_frame_01.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.Button_frame_01.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Button_frame_01.setFrameShape(QFrame.Shape.NoFrame)
        self.Button_frame_01.setFrameShadow(QFrame.Shadow.Plain)
        self.Button_frame_01.setLineWidth(2)
        self.Button_frame_01.setMidLineWidth(0)
        self.gridLayout = QGridLayout(self.Button_frame_01)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.butt_toolB_10 = QToolButton(self.Button_frame_01)
        self.butt_toolB_10.setObjectName(u"butt_toolB_10")
        self.butt_toolB_10.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_10.sizePolicy().hasHeightForWidth())
        self.butt_toolB_10.setSizePolicy(sizePolicy2)
        self.butt_toolB_10.setMinimumSize(QSize(110, 110))
        self.butt_toolB_10.setMaximumSize(QSize(130, 130))
        self.butt_toolB_10.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_10.setIconSize(QSize(70, 70))
        self.butt_toolB_10.setCheckable(True)
        self.butt_toolB_10.setChecked(False)
        self.butt_toolB_10.setAutoRepeatDelay(600)
        self.butt_toolB_10.setAutoRepeatInterval(300)
        self.butt_toolB_10.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_10.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_10.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_10, 2, 1, 1, 1)

        self.butt_toolB_09 = QToolButton(self.Button_frame_01)
        self.butt_toolB_09.setObjectName(u"butt_toolB_09")
        self.butt_toolB_09.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_09.sizePolicy().hasHeightForWidth())
        self.butt_toolB_09.setSizePolicy(sizePolicy2)
        self.butt_toolB_09.setMinimumSize(QSize(110, 110))
        self.butt_toolB_09.setMaximumSize(QSize(130, 130))
        self.butt_toolB_09.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_09.setIconSize(QSize(70, 70))
        self.butt_toolB_09.setCheckable(True)
        self.butt_toolB_09.setChecked(False)
        self.butt_toolB_09.setAutoRepeatDelay(600)
        self.butt_toolB_09.setAutoRepeatInterval(300)
        self.butt_toolB_09.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_09.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_09.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_09, 2, 0, 1, 1)

        self.butt_toolB_01 = QToolButton(self.Button_frame_01)
        self.butt_toolB_01.setObjectName(u"butt_toolB_01")
        self.butt_toolB_01.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_01.sizePolicy().hasHeightForWidth())
        self.butt_toolB_01.setSizePolicy(sizePolicy2)
        self.butt_toolB_01.setMinimumSize(QSize(110, 110))
        self.butt_toolB_01.setMaximumSize(QSize(130, 130))
        self.butt_toolB_01.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_01.setIconSize(QSize(70, 70))
        self.butt_toolB_01.setCheckable(True)
        self.butt_toolB_01.setChecked(False)
        self.butt_toolB_01.setAutoRepeatDelay(600)
        self.butt_toolB_01.setAutoRepeatInterval(300)
        self.butt_toolB_01.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_01.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_01.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_01, 0, 0, 1, 1)

        self.butt_toolB_02 = QToolButton(self.Button_frame_01)
        self.butt_toolB_02.setObjectName(u"butt_toolB_02")
        self.butt_toolB_02.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_02.sizePolicy().hasHeightForWidth())
        self.butt_toolB_02.setSizePolicy(sizePolicy2)
        self.butt_toolB_02.setMinimumSize(QSize(110, 110))
        self.butt_toolB_02.setMaximumSize(QSize(130, 130))
        self.butt_toolB_02.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_02.setIconSize(QSize(70, 70))
        self.butt_toolB_02.setCheckable(True)
        self.butt_toolB_02.setChecked(False)
        self.butt_toolB_02.setAutoRepeatDelay(600)
        self.butt_toolB_02.setAutoRepeatInterval(300)
        self.butt_toolB_02.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_02.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_02.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_02, 0, 1, 1, 1)

        self.butt_toolB_08 = QToolButton(self.Button_frame_01)
        self.butt_toolB_08.setObjectName(u"butt_toolB_08")
        self.butt_toolB_08.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_08.sizePolicy().hasHeightForWidth())
        self.butt_toolB_08.setSizePolicy(sizePolicy2)
        self.butt_toolB_08.setMinimumSize(QSize(110, 110))
        self.butt_toolB_08.setMaximumSize(QSize(130, 130))
        self.butt_toolB_08.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_08.setIconSize(QSize(70, 70))
        self.butt_toolB_08.setCheckable(True)
        self.butt_toolB_08.setChecked(False)
        self.butt_toolB_08.setAutoRepeatDelay(600)
        self.butt_toolB_08.setAutoRepeatInterval(300)
        self.butt_toolB_08.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_08.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_08.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_08, 1, 3, 1, 1)

        self.butt_toolB_07 = QToolButton(self.Button_frame_01)
        self.butt_toolB_07.setObjectName(u"butt_toolB_07")
        self.butt_toolB_07.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_07.sizePolicy().hasHeightForWidth())
        self.butt_toolB_07.setSizePolicy(sizePolicy2)
        self.butt_toolB_07.setMinimumSize(QSize(110, 110))
        self.butt_toolB_07.setMaximumSize(QSize(130, 130))
        self.butt_toolB_07.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_07.setIconSize(QSize(70, 70))
        self.butt_toolB_07.setCheckable(True)
        self.butt_toolB_07.setChecked(False)
        self.butt_toolB_07.setAutoRepeatDelay(600)
        self.butt_toolB_07.setAutoRepeatInterval(300)
        self.butt_toolB_07.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_07.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_07.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_07, 1, 2, 1, 1)

        self.butt_toolB_03 = QToolButton(self.Button_frame_01)
        self.butt_toolB_03.setObjectName(u"butt_toolB_03")
        self.butt_toolB_03.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_03.sizePolicy().hasHeightForWidth())
        self.butt_toolB_03.setSizePolicy(sizePolicy2)
        self.butt_toolB_03.setMinimumSize(QSize(110, 110))
        self.butt_toolB_03.setMaximumSize(QSize(130, 130))
        self.butt_toolB_03.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_03.setIconSize(QSize(70, 70))
        self.butt_toolB_03.setCheckable(True)
        self.butt_toolB_03.setChecked(False)
        self.butt_toolB_03.setAutoRepeatDelay(600)
        self.butt_toolB_03.setAutoRepeatInterval(300)
        self.butt_toolB_03.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_03.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_03.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_03, 0, 2, 1, 1)

        self.butt_toolB_11 = QToolButton(self.Button_frame_01)
        self.butt_toolB_11.setObjectName(u"butt_toolB_11")
        self.butt_toolB_11.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_11.sizePolicy().hasHeightForWidth())
        self.butt_toolB_11.setSizePolicy(sizePolicy2)
        self.butt_toolB_11.setMinimumSize(QSize(110, 110))
        self.butt_toolB_11.setMaximumSize(QSize(130, 130))
        self.butt_toolB_11.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_11.setIconSize(QSize(70, 70))
        self.butt_toolB_11.setCheckable(True)
        self.butt_toolB_11.setChecked(False)
        self.butt_toolB_11.setAutoRepeatDelay(600)
        self.butt_toolB_11.setAutoRepeatInterval(300)
        self.butt_toolB_11.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_11.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_11.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_11, 2, 2, 1, 1)

        self.butt_toolB_06 = QToolButton(self.Button_frame_01)
        self.butt_toolB_06.setObjectName(u"butt_toolB_06")
        self.butt_toolB_06.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_06.sizePolicy().hasHeightForWidth())
        self.butt_toolB_06.setSizePolicy(sizePolicy2)
        self.butt_toolB_06.setMinimumSize(QSize(110, 110))
        self.butt_toolB_06.setMaximumSize(QSize(130, 130))
        self.butt_toolB_06.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_06.setIconSize(QSize(70, 70))
        self.butt_toolB_06.setCheckable(True)
        self.butt_toolB_06.setChecked(False)
        self.butt_toolB_06.setAutoRepeatDelay(600)
        self.butt_toolB_06.setAutoRepeatInterval(300)
        self.butt_toolB_06.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_06.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_06.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_06, 1, 1, 1, 1)

        self.butt_toolB_04 = QToolButton(self.Button_frame_01)
        self.butt_toolB_04.setObjectName(u"butt_toolB_04")
        self.butt_toolB_04.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_04.sizePolicy().hasHeightForWidth())
        self.butt_toolB_04.setSizePolicy(sizePolicy2)
        self.butt_toolB_04.setMinimumSize(QSize(110, 110))
        self.butt_toolB_04.setMaximumSize(QSize(130, 130))
        self.butt_toolB_04.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_04.setIconSize(QSize(70, 70))
        self.butt_toolB_04.setCheckable(True)
        self.butt_toolB_04.setChecked(False)
        self.butt_toolB_04.setAutoRepeatDelay(600)
        self.butt_toolB_04.setAutoRepeatInterval(300)
        self.butt_toolB_04.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_04.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_04.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_04, 0, 3, 1, 1)

        self.butt_toolB_12 = QToolButton(self.Button_frame_01)
        self.butt_toolB_12.setObjectName(u"butt_toolB_12")
        self.butt_toolB_12.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_12.sizePolicy().hasHeightForWidth())
        self.butt_toolB_12.setSizePolicy(sizePolicy2)
        self.butt_toolB_12.setMinimumSize(QSize(110, 110))
        self.butt_toolB_12.setMaximumSize(QSize(130, 130))
        self.butt_toolB_12.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_12.setIconSize(QSize(70, 70))
        self.butt_toolB_12.setCheckable(True)
        self.butt_toolB_12.setChecked(False)
        self.butt_toolB_12.setAutoRepeatDelay(600)
        self.butt_toolB_12.setAutoRepeatInterval(300)
        self.butt_toolB_12.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_12.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_12.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_12, 2, 3, 1, 1)

        self.butt_toolB_05 = QToolButton(self.Button_frame_01)
        self.butt_toolB_05.setObjectName(u"butt_toolB_05")
        self.butt_toolB_05.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.butt_toolB_05.sizePolicy().hasHeightForWidth())
        self.butt_toolB_05.setSizePolicy(sizePolicy2)
        self.butt_toolB_05.setMinimumSize(QSize(110, 110))
        self.butt_toolB_05.setMaximumSize(QSize(130, 130))
        self.butt_toolB_05.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.butt_toolB_05.setIconSize(QSize(70, 70))
        self.butt_toolB_05.setCheckable(True)
        self.butt_toolB_05.setChecked(False)
        self.butt_toolB_05.setAutoRepeatDelay(600)
        self.butt_toolB_05.setAutoRepeatInterval(300)
        self.butt_toolB_05.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.butt_toolB_05.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.butt_toolB_05.setProperty("applyShadow", True)

        self.gridLayout.addWidget(self.butt_toolB_05, 1, 0, 1, 1)


        self.gridLayout_2.addWidget(self.Button_frame_01, 0, 0, 1, 1)

        self.Button_stackedWidget.addWidget(self.page_1)

        self.left_layout.addWidget(self.Button_stackedWidget)

        self.preference_frame = QFrame(self.frame)
        self.preference_frame.setObjectName(u"preference_frame")
        self.preference_frame.setMinimumSize(QSize(600, 210))
        self.preference_frame.setMaximumSize(QSize(600, 210))
        self.preference_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.preference_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.preference_frame)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.example_layout = QVBoxLayout()
        self.example_layout.setSpacing(0)
        self.example_layout.setObjectName(u"example_layout")
        self.Example_groupB = QGroupBox(self.preference_frame)
        self.Example_groupB.setObjectName(u"Example_groupB")
        sizePolicy1.setHeightForWidth(self.Example_groupB.sizePolicy().hasHeightForWidth())
        self.Example_groupB.setSizePolicy(sizePolicy1)
        self.Example_groupB.setMinimumSize(QSize(120, 120))
        self.Example_groupB.setMaximumSize(QSize(120, 120))
        self.Example_groupB.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_5 = QHBoxLayout(self.Example_groupB)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.Example_toolB = QToolButton(self.Example_groupB)
        self.Example_toolB.setObjectName(u"Example_toolB")
        sizePolicy1.setHeightForWidth(self.Example_toolB.sizePolicy().hasHeightForWidth())
        self.Example_toolB.setSizePolicy(sizePolicy1)
        self.Example_toolB.setMinimumSize(QSize(100, 100))
        self.Example_toolB.setMaximumSize(QSize(100, 100))
        self.Example_toolB.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Example_toolB.setIconSize(QSize(64, 64))
        self.Example_toolB.setCheckable(False)
        self.Example_toolB.setChecked(False)
        self.Example_toolB.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.horizontalLayout_5.addWidget(self.Example_toolB)


        self.example_layout.addWidget(self.Example_groupB, 0, Qt.AlignmentFlag.AlignHCenter)

        self.ico_groupB = QGroupBox(self.preference_frame)
        self.ico_groupB.setObjectName(u"ico_groupB")
        self.ico_groupB.setMinimumSize(QSize(150, 70))
        self.ico_groupB.setMaximumSize(QSize(120, 70))
        self.ico_groupB.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_6 = QHBoxLayout(self.ico_groupB)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 5)
        self.Browse_ico_diy_toolB = QPushButton(self.ico_groupB)
        self.Browse_ico_diy_toolB.setObjectName(u"Browse_ico_diy_toolB")
        sizePolicy1.setHeightForWidth(self.Browse_ico_diy_toolB.sizePolicy().hasHeightForWidth())
        self.Browse_ico_diy_toolB.setSizePolicy(sizePolicy1)
        self.Browse_ico_diy_toolB.setMinimumSize(QSize(40, 40))
        self.Browse_ico_diy_toolB.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.Browse_ico_diy_toolB)

        self.Browse_ico_lib_toolB = QPushButton(self.ico_groupB)
        self.Browse_ico_lib_toolB.setObjectName(u"Browse_ico_lib_toolB")
        self.Browse_ico_lib_toolB.setMinimumSize(QSize(40, 40))
        self.Browse_ico_lib_toolB.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.Browse_ico_lib_toolB)

        self.switch_ico_lib_toolB = QPushButton(self.ico_groupB)
        self.switch_ico_lib_toolB.setObjectName(u"switch_ico_lib_toolB")
        self.switch_ico_lib_toolB.setMinimumSize(QSize(40, 40))
        self.switch_ico_lib_toolB.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.switch_ico_lib_toolB)


        self.example_layout.addWidget(self.ico_groupB, 0, Qt.AlignmentFlag.AlignHCenter)


        self.horizontalLayout_2.addLayout(self.example_layout)

        self.funcrion_widget = QTabWidget(self.preference_frame)
        self.funcrion_widget.setObjectName(u"funcrion_widget")
        self.funcrion_widget.setMaximumSize(QSize(270, 16777215))
        self.app_tab = QWidget()
        self.app_tab.setObjectName(u"app_tab")
        self.layoutWidget = QWidget(self.app_tab)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1, 1, 261, 171))
        self.application_layout = QVBoxLayout(self.layoutWidget)
        self.application_layout.setSpacing(5)
        self.application_layout.setObjectName(u"application_layout")
        self.application_layout.setContentsMargins(0, 0, 0, 0)
        self.title_layout = QHBoxLayout()
        self.title_layout.setSpacing(5)
        self.title_layout.setObjectName(u"title_layout")
        self.app_title_lable = QLabel(self.layoutWidget)
        self.app_title_lable.setObjectName(u"app_title_lable")
        self.app_title_lable.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.app_title_lable.setLineWidth(0)
        self.app_title_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.title_layout.addWidget(self.app_title_lable)

        self.app_title_lineE = QLineEdit(self.layoutWidget)
        self.app_title_lineE.setObjectName(u"app_title_lineE")
        self.app_title_lineE.setMinimumSize(QSize(180, 30))
        self.app_title_lineE.setMaximumSize(QSize(180, 16777215))

        self.title_layout.addWidget(self.app_title_lineE)


        self.application_layout.addLayout(self.title_layout)

        self.app_but_layout = QHBoxLayout()
        self.app_but_layout.setSpacing(5)
        self.app_but_layout.setObjectName(u"app_but_layout")
        self.app_lable = QLabel(self.layoutWidget)
        self.app_lable.setObjectName(u"app_lable")
        self.app_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.app_but_layout.addWidget(self.app_lable)

        self.app_choice_toolB = QToolButton(self.layoutWidget)
        self.app_choice_toolB.setObjectName(u"app_choice_toolB")
        self.app_choice_toolB.setMinimumSize(QSize(180, 30))
        self.app_choice_toolB.setMaximumSize(QSize(180, 16777215))

        self.app_but_layout.addWidget(self.app_choice_toolB)


        self.application_layout.addLayout(self.app_but_layout)

        self.app_path_layout = QHBoxLayout()
        self.app_path_layout.setSpacing(5)
        self.app_path_layout.setObjectName(u"app_path_layout")
        self.app_path_lable = QLabel(self.layoutWidget)
        self.app_path_lable.setObjectName(u"app_path_lable")
        self.app_path_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.app_path_layout.addWidget(self.app_path_lable)

        self.app_path_lineE = QLineEdit(self.layoutWidget)
        self.app_path_lineE.setObjectName(u"app_path_lineE")
        self.app_path_lineE.setMinimumSize(QSize(180, 30))
        self.app_path_lineE.setMaximumSize(QSize(180, 30))
        self.app_path_lineE.setReadOnly(True)

        self.app_path_layout.addWidget(self.app_path_lineE)


        self.application_layout.addLayout(self.app_path_layout)

        self.long_press_layout = QHBoxLayout()
        self.long_press_layout.setSpacing(5)
        self.long_press_layout.setObjectName(u"long_press_layout")
        self.app_long_press_lable = QLabel(self.layoutWidget)
        self.app_long_press_lable.setObjectName(u"app_long_press_lable")
        self.app_long_press_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.long_press_layout.addWidget(self.app_long_press_lable)

        self.app_long_press_comboB = QComboBox(self.layoutWidget)
        self.app_long_press_comboB.setObjectName(u"app_long_press_comboB")
        sizePolicy1.setHeightForWidth(self.app_long_press_comboB.sizePolicy().hasHeightForWidth())
        self.app_long_press_comboB.setSizePolicy(sizePolicy1)
        self.app_long_press_comboB.setMinimumSize(QSize(180, 0))
        self.app_long_press_comboB.setMaximumSize(QSize(180, 30))

        self.long_press_layout.addWidget(self.app_long_press_comboB)


        self.application_layout.addLayout(self.long_press_layout)

        self.funcrion_widget.addTab(self.app_tab, "")
        self.shortcut_tab = QWidget()
        self.shortcut_tab.setObjectName(u"shortcut_tab")
        self.layoutWidget1 = QWidget(self.shortcut_tab)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(0, 0, 261, 171))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.sh_title_layout = QHBoxLayout()
        self.sh_title_layout.setSpacing(5)
        self.sh_title_layout.setObjectName(u"sh_title_layout")
        self.sh_title_lable = QLabel(self.layoutWidget1)
        self.sh_title_lable.setObjectName(u"sh_title_lable")
        self.sh_title_lable.setMaximumSize(QSize(40, 50))
        self.sh_title_lable.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sh_title_lable.setLineWidth(0)
        self.sh_title_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.sh_title_layout.addWidget(self.sh_title_lable, 0, Qt.AlignmentFlag.AlignRight)

        self.sh_title_lineE = QLineEdit(self.layoutWidget1)
        self.sh_title_lineE.setObjectName(u"sh_title_lineE")
        self.sh_title_lineE.setMinimumSize(QSize(140, 30))
        self.sh_title_lineE.setMaximumSize(QSize(140, 30))

        self.sh_title_layout.addWidget(self.sh_title_lineE, 0, Qt.AlignmentFlag.AlignRight)


        self.verticalLayout_3.addLayout(self.sh_title_layout)

        self.sh_hc1_layout = QHBoxLayout()
        self.sh_hc1_layout.setSpacing(5)
        self.sh_hc1_layout.setObjectName(u"sh_hc1_layout")
        self.sh_hotckey1_lable = QLabel(self.layoutWidget1)
        self.sh_hotckey1_lable.setObjectName(u"sh_hotckey1_lable")
        self.sh_hotckey1_lable.setMaximumSize(QSize(60, 50))
        self.sh_hotckey1_lable.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sh_hotckey1_lable.setLineWidth(0)
        self.sh_hotckey1_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.sh_hc1_layout.addWidget(self.sh_hotckey1_lable, 0, Qt.AlignmentFlag.AlignRight)

        self.sh_hc1_keyEdit = QKeySequenceEdit(self.layoutWidget1)
        self.sh_hc1_keyEdit.setObjectName(u"sh_hc1_keyEdit")
        self.sh_hc1_keyEdit.setMinimumSize(QSize(140, 30))
        self.sh_hc1_keyEdit.setMaximumSize(QSize(140, 30))

        self.sh_hc1_layout.addWidget(self.sh_hc1_keyEdit, 0, Qt.AlignmentFlag.AlignRight)


        self.verticalLayout_3.addLayout(self.sh_hc1_layout)

        self.sh_hc2_layout = QHBoxLayout()
        self.sh_hc2_layout.setSpacing(5)
        self.sh_hc2_layout.setObjectName(u"sh_hc2_layout")
        self.sh_hotckey2_lable = QLabel(self.layoutWidget1)
        self.sh_hotckey2_lable.setObjectName(u"sh_hotckey2_lable")
        self.sh_hotckey2_lable.setMaximumSize(QSize(60, 50))
        self.sh_hotckey2_lable.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sh_hotckey2_lable.setLineWidth(0)
        self.sh_hotckey2_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.sh_hc2_layout.addWidget(self.sh_hotckey2_lable, 0, Qt.AlignmentFlag.AlignRight)

        self.sh_hc2_keyEdit = QKeySequenceEdit(self.layoutWidget1)
        self.sh_hc2_keyEdit.setObjectName(u"sh_hc2_keyEdit")
        self.sh_hc2_keyEdit.setMinimumSize(QSize(140, 30))
        self.sh_hc2_keyEdit.setMaximumSize(QSize(140, 30))

        self.sh_hc2_layout.addWidget(self.sh_hc2_keyEdit, 0, Qt.AlignmentFlag.AlignRight)


        self.verticalLayout_3.addLayout(self.sh_hc2_layout)

        self.funcrion_widget.addTab(self.shortcut_tab, "")
        self.action_tab = QWidget()
        self.action_tab.setObjectName(u"action_tab")
        self.layoutWidget2 = QWidget(self.action_tab)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(0, 0, 261, 171))
        self.action_layout = QVBoxLayout(self.layoutWidget2)
        self.action_layout.setSpacing(5)
        self.action_layout.setObjectName(u"action_layout")
        self.action_layout.setContentsMargins(0, 0, 0, 0)
        self.action_title_layout = QHBoxLayout()
        self.action_title_layout.setSpacing(5)
        self.action_title_layout.setObjectName(u"action_title_layout")
        self.action_title_lable = QLabel(self.layoutWidget2)
        self.action_title_lable.setObjectName(u"action_title_lable")
        self.action_title_lable.setMaximumSize(QSize(50, 40))
        self.action_title_lable.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.action_title_lable.setLineWidth(0)
        self.action_title_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.action_title_layout.addWidget(self.action_title_lable, 0, Qt.AlignmentFlag.AlignRight)

        self.action_title_lineE = QLineEdit(self.layoutWidget2)
        self.action_title_lineE.setObjectName(u"action_title_lineE")
        self.action_title_lineE.setMinimumSize(QSize(140, 30))
        self.action_title_lineE.setMaximumSize(QSize(140, 16777215))

        self.action_title_layout.addWidget(self.action_title_lineE, 0, Qt.AlignmentFlag.AlignRight)


        self.action_layout.addLayout(self.action_title_layout)

        self.action_choice_layout = QHBoxLayout()
        self.action_choice_layout.setSpacing(5)
        self.action_choice_layout.setObjectName(u"action_choice_layout")
        self.action__lable = QLabel(self.layoutWidget2)
        self.action__lable.setObjectName(u"action__lable")
        self.action__lable.setMaximumSize(QSize(40, 50))
        self.action__lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.action_choice_layout.addWidget(self.action__lable, 0, Qt.AlignmentFlag.AlignRight)

        self.action_comboB = QComboBox(self.layoutWidget2)
        self.action_comboB.setObjectName(u"action_comboB")
        sizePolicy1.setHeightForWidth(self.action_comboB.sizePolicy().hasHeightForWidth())
        self.action_comboB.setSizePolicy(sizePolicy1)
        self.action_comboB.setMinimumSize(QSize(140, 0))
        self.action_comboB.setMaximumSize(QSize(140, 30))

        self.action_choice_layout.addWidget(self.action_comboB, 0, Qt.AlignmentFlag.AlignRight)


        self.action_layout.addLayout(self.action_choice_layout)

        self.funcrion_widget.addTab(self.action_tab, "")

        self.horizontalLayout_2.addWidget(self.funcrion_widget)

        self.manager_gBox = QGroupBox(self.preference_frame)
        self.manager_gBox.setObjectName(u"manager_gBox")
        self.manager_gBox.setMinimumSize(QSize(140, 170))
        self.manager_gBox.setMaximumSize(QSize(140, 190))
        self.verticalLayout_2 = QVBoxLayout(self.manager_gBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.butt_page_layout = QHBoxLayout()
        self.butt_page_layout.setSpacing(5)
        self.butt_page_layout.setObjectName(u"butt_page_layout")
        self.remove_page_toolB = QPushButton(self.manager_gBox)
        self.remove_page_toolB.setObjectName(u"remove_page_toolB")
        sizePolicy1.setHeightForWidth(self.remove_page_toolB.sizePolicy().hasHeightForWidth())
        self.remove_page_toolB.setSizePolicy(sizePolicy1)
        self.remove_page_toolB.setMinimumSize(QSize(30, 30))
        self.remove_page_toolB.setMaximumSize(QSize(40, 40))

        self.butt_page_layout.addWidget(self.remove_page_toolB)

        self.add_page_toolB = QPushButton(self.manager_gBox)
        self.add_page_toolB.setObjectName(u"add_page_toolB")
        sizePolicy1.setHeightForWidth(self.add_page_toolB.sizePolicy().hasHeightForWidth())
        self.add_page_toolB.setSizePolicy(sizePolicy1)
        self.add_page_toolB.setMinimumSize(QSize(30, 30))
        self.add_page_toolB.setMaximumSize(QSize(40, 40))
        self.add_page_toolB.setBaseSize(QSize(25, 25))
        self.add_page_toolB.setMouseTracking(False)
        self.add_page_toolB.setTabletTracking(False)
        self.add_page_toolB.setFlat(False)

        self.butt_page_layout.addWidget(self.add_page_toolB)


        self.verticalLayout_2.addLayout(self.butt_page_layout)

        self.current_page_lable = QLabel(self.manager_gBox)
        self.current_page_lable.setObjectName(u"current_page_lable")
        self.current_page_lable.setMinimumSize(QSize(80, 40))
        self.current_page_lable.setMaximumSize(QSize(80, 40))
        self.current_page_lable.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.current_page_lable.setFrameShape(QFrame.Shape.StyledPanel)
        self.current_page_lable.setFrameShadow(QFrame.Shadow.Plain)
        self.current_page_lable.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.current_page_lable, 0, Qt.AlignmentFlag.AlignHCenter)

        self.back_next_layout = QHBoxLayout()
        self.back_next_layout.setSpacing(5)
        self.back_next_layout.setObjectName(u"back_next_layout")
        self.back_page_pushB = QPushButton(self.manager_gBox)
        self.back_page_pushB.setObjectName(u"back_page_pushB")
        sizePolicy1.setHeightForWidth(self.back_page_pushB.sizePolicy().hasHeightForWidth())
        self.back_page_pushB.setSizePolicy(sizePolicy1)
        self.back_page_pushB.setMinimumSize(QSize(40, 40))
        self.back_page_pushB.setMaximumSize(QSize(40, 40))

        self.back_next_layout.addWidget(self.back_page_pushB)

        self.next_page_pushB = QPushButton(self.manager_gBox)
        self.next_page_pushB.setObjectName(u"next_page_pushB")
        sizePolicy1.setHeightForWidth(self.next_page_pushB.sizePolicy().hasHeightForWidth())
        self.next_page_pushB.setSizePolicy(sizePolicy1)
        self.next_page_pushB.setMinimumSize(QSize(40, 40))
        self.next_page_pushB.setMaximumSize(QSize(40, 40))

        self.back_next_layout.addWidget(self.next_page_pushB)


        self.verticalLayout_2.addLayout(self.back_next_layout)


        self.horizontalLayout_2.addWidget(self.manager_gBox)

        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 1)

        self.left_layout.addWidget(self.preference_frame)


        self.horizontalLayout.addLayout(self.left_layout)

        self.right_layout = QVBoxLayout()
        self.right_layout.setSpacing(10)
        self.right_layout.setObjectName(u"right_layout")
        self.treeWidget = QTreeWidget(self.frame)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setMaximumSize(QSize(250, 430))

        self.right_layout.addWidget(self.treeWidget)

        self.save_frame = QFrame(self.frame)
        self.save_frame.setObjectName(u"save_frame")
        self.save_frame.setMinimumSize(QSize(250, 210))
        self.save_frame.setMaximumSize(QSize(250, 210))
        self.save_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.save_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.save_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.save_pushB = QPushButton(self.save_frame)
        self.save_pushB.setObjectName(u"save_pushB")
        sizePolicy1.setHeightForWidth(self.save_pushB.sizePolicy().hasHeightForWidth())
        self.save_pushB.setSizePolicy(sizePolicy1)
        self.save_pushB.setMinimumSize(QSize(130, 30))
        self.save_pushB.setMaximumSize(QSize(130, 30))

        self.verticalLayout.addWidget(self.save_pushB, 0, Qt.AlignmentFlag.AlignHCenter)

        self.save_new_pushB = QPushButton(self.save_frame)
        self.save_new_pushB.setObjectName(u"save_new_pushB")
        sizePolicy1.setHeightForWidth(self.save_new_pushB.sizePolicy().hasHeightForWidth())
        self.save_new_pushB.setSizePolicy(sizePolicy1)
        self.save_new_pushB.setMinimumSize(QSize(130, 30))
        self.save_new_pushB.setMaximumSize(QSize(130, 30))

        self.verticalLayout.addWidget(self.save_new_pushB, 0, Qt.AlignmentFlag.AlignHCenter)


        self.right_layout.addWidget(self.save_frame)


        self.horizontalLayout.addLayout(self.right_layout)


        self.retranslateUi(stream_bandito)

        self.Button_stackedWidget.setCurrentIndex(0)
        self.funcrion_widget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(stream_bandito)
    # setupUi

    def retranslateUi(self, stream_bandito):
        self.butt_toolB_10.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_09.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_01.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_01.setProperty("shadowPreset", QCoreApplication.translate("stream_bandito", u"button", None))
        self.butt_toolB_02.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_02.setProperty("shadowPreset", QCoreApplication.translate("stream_bandito", u"glow_pink", None))
        self.butt_toolB_08.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_07.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_03.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_11.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_06.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_04.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_12.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.butt_toolB_05.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.Example_groupB.setTitle("")
        self.Example_toolB.setText(QCoreApplication.translate("stream_bandito", u"...", None))
        self.ico_groupB.setTitle(QCoreApplication.translate("stream_bandito", u"Ico", None))
        self.Browse_ico_diy_toolB.setText(QCoreApplication.translate("stream_bandito", u"Browse icon", None))
        self.Browse_ico_lib_toolB.setText(QCoreApplication.translate("stream_bandito", u"Lib Icon", None))
        self.switch_ico_lib_toolB.setText(QCoreApplication.translate("stream_bandito", u"Lib Icon", None))
        self.app_title_lable.setText(QCoreApplication.translate("stream_bandito", u"Title:", None))
        self.app_lable.setText(QCoreApplication.translate("stream_bandito", u"App:", None))
        self.app_choice_toolB.setText(QCoreApplication.translate("stream_bandito", u"Browse", None))
        self.app_path_lable.setText(QCoreApplication.translate("stream_bandito", u"Path:", None))
        self.app_long_press_lable.setText(QCoreApplication.translate("stream_bandito", u"Long Press:", None))
        self.funcrion_widget.setTabText(self.funcrion_widget.indexOf(self.app_tab), QCoreApplication.translate("stream_bandito", u"Application", None))
        self.sh_title_lable.setText(QCoreApplication.translate("stream_bandito", u"Title:", None))
        self.sh_hotckey1_lable.setText(QCoreApplication.translate("stream_bandito", u"Hotkey 1:", None))
        self.sh_hotckey2_lable.setText(QCoreApplication.translate("stream_bandito", u"Hotkey 2:", None))
        self.funcrion_widget.setTabText(self.funcrion_widget.indexOf(self.shortcut_tab), QCoreApplication.translate("stream_bandito", u"Shortcuts", None))
        self.action_title_lable.setText(QCoreApplication.translate("stream_bandito", u"Title:", None))
        self.action__lable.setText(QCoreApplication.translate("stream_bandito", u"Action:", None))
        self.funcrion_widget.setTabText(self.funcrion_widget.indexOf(self.action_tab), QCoreApplication.translate("stream_bandito", u"Action", None))
        self.manager_gBox.setTitle(QCoreApplication.translate("stream_bandito", u"Manager page", None))
        self.remove_page_toolB.setText(QCoreApplication.translate("stream_bandito", u"-", None))
        self.add_page_toolB.setText(QCoreApplication.translate("stream_bandito", u"+", None))
        self.current_page_lable.setText("")
        self.back_page_pushB.setText(QCoreApplication.translate("stream_bandito", u"Back", None))
        self.next_page_pushB.setText(QCoreApplication.translate("stream_bandito", u"Next", None))
        self.save_pushB.setText(QCoreApplication.translate("stream_bandito", u"Save Change", None))
        self.save_new_pushB.setText(QCoreApplication.translate("stream_bandito", u"Save Preset", None))
        pass
    # retranslateUi

